apiVersion: apps/v1
kind: Deployment
metadata:
  name: hit-deployment
  namespace: hit
  labels:
    app: hit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hit
  template:
    metadata:
      labels:
        app: hit
    spec:
      containers:
      - name: medusa
        image: sdmoradi/hit-app:latest
        ports:
        - containerPort: 5000