name: ci-cd
on:
  push:
    branches:
      - "master"
jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: changed-files
        uses: ahmadnassri/action-changed-files@v1
      - run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            echo "$file has changed"
          done
      - if: contains(steps.changed-files.outputs.files, 'requirements.txt')
        run: |
          cat version.txt | awk '{split($0,a,"."); print a[1]+1 "." a[2] "." a[3]}' | tee version.txt
          echo "commit=True" >> $GITHUB_ENV

      - if: contains(steps.changed-files.outputs.files, 'app.py')
        run: |
          cat version.txt | awk '{split($0,a,"."); print a[1] "." a[2]+1 "." a[3]}' | tee version.txt
          echo "commit=True" >> $GITHUB_ENV

      - if: contains(steps.changed-files.outputs.files, 'README.md')
        run: |
          cat version.txt | awk '{split($0,a,"."); print a[1] "." a[2] "." a[3]+1}' | tee version.txt
          echo "commit=True" >> $GITHUB_ENV

      - name: change-commit-push
        if: ${{env.commit}} == 'True'
        run: |
          git config --global user.name "sdmoradi"
          git config --global user.email "sdmrd67@gmail.com"
          git add version.txt
          git commit -m "change patch version"
          git push
