name: ci-cd
on:
  push:
    branches:
      - "master"
jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: diff-requirements
        id: diff-requirements
        run : |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { $_ -match 'requirements.txt' }
          $HasDiff = $SourceDiff.Length -gt 0
          Write-Host "::set-output name=req_changed::$HasDiff"
      - name : change-major
        if: steps.diff-requirements.outputs.req_changed == 'True'
        run: cat version.txt | awk '{split($0,a,"."); print a[1]+1 "." a[2] "." a[3]}' | tee version.txt

      - name: diff-app
        id: diff-app
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { $_ -match 'app.py' }
          $HasDiff = $SourceDiff.Length -gt 0
          Write-Host "::set-output name=app_changed::$HasDiff"
      - name: change-minor
        if: steps.diff-app.outputs.app_changed == 'True'
        run: cat version.txt | awk '{split($0,a,"."); print a[1] "." a[2]+1 "." a[3]}' | tee version.txt

      - name: diff-readme
        id: diff-readme
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { $_ -match 'README.md' }
          $HasDiff = $SourceDiff.Length -gt 0
          Write-Host "::set-output name=readme_changed::$HasDiff"
      - name: change-patch
        if: steps.diff-readme.outputs.readme_changed == 'True'
        run: cat version.txt | awk '{split($0,a,"."); print a[1] "." a[2] "." a[3]+1}' | tee version.txt

      - name: change-commit-push
        if: steps.diff-requirements.outputs.req_changed == 'True' || steps.diff-app.outputs.app_changed == 'True' || steps.diff-readme.outputs.readme_changed == 'True'
        run: |
          git config --global user.name "sdmoradi"
          git config --global user.email "sdmrd67@gmail.com"
          git add version.txt
          git commit -m "change patch version"
          git push
